version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/creatorkostas/yamcs-simulator"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"